### ISSUE TITLE
The workspace named "rntypescriptBoilerplate" does not contain a scheme named "rntypescriptBoilerplate"

### ISSUE THREAD

**Issue by marklanham** [WrathChaos/react-native-typescript-zustand-boilerplate#3]
Just installed the latest version of [react-native-typescript-zustand-boilerplate](https://github.com/WrathChaos/react-native-typescript-zustand-boilerplate). 

I can get it to run using Xcode but when I try to run it using the command line (Terminal) I get the following error:

```
error Failed to build iOS project. "xcodebuild" exited with error code '65'. To debug build logs further, consider building your app with Xcode.app, by opening 'rntypescriptBoilerplate.xcworkspace'.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace rntypescriptBoilerplate.xcworkspace -configuration Debug -scheme rntypescriptBoilerplate -destination id=970E7D0A-2E36-4317-A3D0-57FE77AFF2FF

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES


2024-03-02 00:15:59.668 xcodebuild[12405:106552] Writing error result bundle to /var/folders/nh/8_l342hx2ll8psk4wpphm2fr0000gn/T/ResultBundle_2024-02-03_00-15-0059.xcresult
xcodebuild: error: The workspace named "rntypescriptBoilerplate" does not contain a scheme named "rntypescriptBoilerplate". The "-list" option can be used to find the names of the schemes in the workspace.
```

Node: **18.12.1**
Xcode: **Version 15.2 (15C500b)**
Simulator: **iPhone 15 Pro Max (17.2)**
Cocoapods: **1.15.2**
React Native: **0.73.3**
macOS: **Sonoma: 14.1.1**

**Comment by kuraydev** [comment]
Hello @marklanham 

Fixing it right away, thank you so much for reporting!

**Comment by kuraydev** [comment]
@marklanham hello again,

I believe this time I fixed the old issue, can you please try again?

**Comment by eduard1dev** [comment]
Got this error in the latest version.

just rename the `RNTypescriptBoilerplate.xcscheme` file to  `rntypescriptBoilerplate.xcscheme`
